### PR TITLE
Feature: create example components

### PR DESCRIPTION
**Pull request by woutermont**
Signed-off-by: Wouter Termont <woutermont@gmail.com>

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=653481515) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by BelgianNoise** [comment]
CI Error:
image

Getting the same error when i run `npm install` locally in the folder `packages/semcon-components`.
Also, when i do this it will try and download the `core` package from npm, where an older incompatible version is hosted.

**Comment by lem-onade** [comment]
> CI Error:
> image
> 
> Getting the same error when i run `npm install` locally in the folder `packages/semcon-components`.
> Also, when i do this it will try and download the `core` package from npm, where an older incompatible version is hosted.

**Comment by BelgianNoise** [comment]
Example components:
image
image

**Review by woutermont — COMMENTED** [review]
Not sure why there are Core, Node and SDK additions in here as well. @lem-onade, are these not present in Develop anymore because they are from earlier versions of the class-diagram?

**Comment by stijn** [comment]
You've tagged the wrong person.

**Review by woutermont — COMMENTED** [review]
Approved.

**Pull request merged**
